### ISSUE TITLE
No LICENSE in source

### ISSUE THREAD

**Issue by headius** [abego/treelayout#3]
Hopefully the source *is* licensed under something suitably friendly, like Apache-2 or EPL?

**Comment by abego** [comment]
Sorry, I don't understand. Please give some more details. 

The source files start with a comment holding the license text ('...[The "BSD license"]...'). In addition a file "LICENSE.txt" exists in the "src" directory of "org.abego.treelayout" (and some other places).

**Comment by headius** [comment]
Ahhh I see. OK...I would recommend a top-level LICENSE file because that is where most people (like me) and license-auditing tools will look. And BSD is just fine. Perhaps add more prominent links on project sites or README because I did not find it after a few minutes looking.

**Comment by abego** [comment]
Thanks for your hint. I added a top-level LICENSE file. 

The project website (http://treelayout.sourceforge.net) already has a very prominent link to the license text via the top level TOC (see the "License" chapter).

**Comment by headius** [comment]
Ahh yes. When I searched for treelayout, I found the Google Code page first, which sent me to Github. I didn't follow the additional hint to check Sourceforge for the actual home page. In any case, glad to see the top-level LICENSE file now. Thanks!
