### ISSUE TITLE
Antlr classes should be excluded or shaded so they don't overlap

### ISSUE THREAD

**Issue by headius** [abego/treelayout#4]
We are using treelayout for the jruby+truffle research project under jruby/jruby, and recently started using antlr 4 and treelayout.

Unfortunately, both jruby+truffle and treelayout are shading antlr into the artifact, so they overlap and produce warnings from Maven (that could mean we're introducing some hard-to-find bugs):

```
[INFO] --- maven-shade-plugin:2.1:shade (create lib/jruby-truffle.jar) @ jruby-truffle ---
[INFO] Including org.yaml:snakeyaml:jar:1.14 in the shaded jar.
[INFO] Including org.antlr:antlr4-runtime:jar:4.5 in the shaded jar.
[INFO] Including org.abego.treelayout:org.abego.treelayout.core:jar:1.0.1 in the shaded jar.
[INFO] Including com.oracle:truffle:jar:0.7 in the shaded jar.
[WARNING] antlr4-runtime-4.5.jar, org.abego.treelayout.core-1.0.1.jar define 19 overlappping classes: 
[WARNING]   - org.abego.treelayout.TreeLayout$DumpConfiguration
[WARNING]   - org.abego.treelayout.TreeForTreeLayout
[WARNING]   - org.abego.treelayout.internal.util.java.lang.IterableUtil
[WARNING]   - org.abego.treelayout.Configuration
[WARNING]   - org.abego.treelayout.util.DefaultTreeForTreeLayout
[WARNING]   - org.abego.treelayout.TreeLayout$NormalizedPosition
[WARNING]   - org.abego.treelayout.internal.util.java.util.IteratorUtil
[WARNING]   - org.abego.treelayout.internal.util.java.lang.IterableUtil$ReverseIterable
[WARNING]   - org.abego.treelayout.util.FixedNodeExtentProvider
[WARNING]   - org.abego.treelayout.util.AbstractTreeForTreeLayout
[WARNING]   - 9 more...
[WARNING] maven-shade-plugin has detected that some .class files
[WARNING] are present in two or more JARs. When this happens, only
[WARNING] one single version of the class is copied in the uberjar.
[WARNING] Usually this is not harmful and you can skeep these
[WARNING] warnings, otherwise try to manually exclude artifacts
[WARNING] based on mvn dependency:tree -Ddetail=true and the above
[WARNING] output
[WARNING] See http://docs.codehaus.org/display/MAVENUSER/Shade+Plugin
```

We both need to make some changes.

1. jruby+truffle *needs* to shade antlr because it is intended to be a free-standing, all-in-one jar. However, we should shade it with renaming since it is a popular library certain to collide with other projects. cc @chrisseaton
2. treelayout's maven artifacts *should not* shade antlr for at least one base artifact. It should specify it as a transitive dependency, which would resolve these warnings for jruby+truffle. If you want to push an "all-in-one" artifact, that should be done as a separate artifact in Maven, and it should probably hide antlr for the same reasons as in (1) above.

**Comment by headius** [comment]
Fixed title to better reflect proposed course of action.

**Comment by abego** [comment]
treelayout has no dependencies to antlr classes. The only dependency is the one to junit, but only in the test scope. 

I don't see, how I could help you. I guess you need to contact the antlr4 project to fix the issue you are reporting.


(From my understanding this is not a "treelayout" issue. I am going to close this issue in a week if I don't hear something different from you.)

**Comment by chrisseaton** [comment]
Yes, I think it's Antlr that put `org.abego.treelayout` inside `antlr4-runtime-4.5`. I have no idea why they'd choose to do that. Maybe it was a mistake?

They're gone in `4.5.1-1`. I'll try updating to that.

But I agree with @abego this looks like maybe the fault of Antlr, rather than this repository.

**Comment by chrisseaton** [comment]
It looks like maybe Antlr were expressing both a proper Maven dependency on tree layout, and including it in a jar not marked as a complete or uber jar?

https://github.com/antlr/antlr4/issues/216

**Comment by chrisseaton** [comment]
Yes updating to `4.5.1-1` seems to have fixed it.

**Comment by headius** [comment]
Excellent, thanks @chrisseaton for figuring it out. Sorry for the false alarm, @abego!
